# keys from rails' credentials are added under "credentials" (cf config_add_credentials.rb)
france_connect:
  host: "fcp.integ01.dev-franceconnect.fr"
  identifier: <%= Rails.application.credentials.france_connect.identifier %>
  redirect_uri: "http://localhost:3000/callback"
  secret: <%= Rails.application.credentials.france_connect.secret %>
hubee:
  base_url: "https://api.bas.hubee.numerique.gouv.fr"
  token_url: "https://auth.bas.hubee.numerique.gouv.fr/oauth2/token"
  client_id: <%= Rails.application.credentials.hubee.client_id %>
  client_secret: <%= Rails.application.credentials.hubee.client_secret %>
