credentials:
  database:
    username: <%= Rails.application.credentials.database.username %>
    password: <%= Rails.application.credentials.database.password %>
france_connect:
  host: "fcp.integ01.dev-franceconnect.fr"
  identifier: "211286433e39cce01db448d80181bdfd005554b19cd51b3fe7943f6b3b86ab6e"
  redirect_uri: "http://localhost:3000/callback"
  secret: "2791a731e6a59f56b6b4dd0d08c9b1f593b5f3658b9fd731cb24248e2669af4b"
