# keys from rails' credentials are added under "credentials" (cf config_add_credentials.rb)
api_particulier:
  base_url: "https://staging.particulier.api.gouv.fr"
france_connect:
  host: "fcp-low.sbx.dev-franceconnect.fr"
  identifier: <%= Rails.application.credentials.france_connect.identifier %>
  redirect_uri: "http://localhost:3000/callback"
  secret: <%= Rails.application.credentials.france_connect.secret %>
good_job:
  username: <%= Rails.application.credentials.good_job.username %>
  password: <%= Rails.application.credentials.good_job.password %>
hubee:
  base_url: "https://api.bas.hubee.numerique.gouv.fr"
  token_url: "https://auth.bas.hubee.numerique.gouv.fr/oauth2/token"
  client_id: <%= Rails.application.credentials.hubee.osl.client_id %>
  client_secret: <%= Rails.application.credentials.hubee.osl.client_secret %>
sentry:
  dsn: "real_dsn_to_setup_in_env_settings"
